### DISCUSSION TITLE
Option to transparently Write on read if no secret exists

### DISCUSSION THREAD

**Discussion by psych0d0g** [ansible-collections/community.hashi_vault#319] [Ideas]
i would love to have a feature to basically mimic the ansible.builtin.password lookup plugin with hashi_vault's lookup plugin:

Exerpt from the password lookup plugin docs:
```
Generates a random plaintext password and stores it in a file at a given filepath.
If the file exists previously, it will retrieve its contents, behaving just like with_file.
```

So i would love to be able to just define a lookup somewhere in my role, and if there is no corresponding secret found in hashicorp vault, it should create one automatically for future reference and store it in the supplied "path" in vault, if there is a secret found, just return what is already existing.

that way one could write roles and playbooks without having to ever deal with secrets manually at all, just let the lookup plugin do the generation and storage of secrets in hashicorp vault on demand.

What do you think?

**Comment by briantist** [comment]
Hi @psych0d0g welcome!

This is an interesting proposal, but there are a few possible issues with it.

First is that generally in lookups, we don't really want to be changing state, if we can help it. The `password` lookup is an older lookup and I'm not sure that pattern would be accepted today, but also it changes what is meant to be a file dedicated for the purpose, so it's relatively benign.

That being said, we do already have a [lookup (`vault_write`) that rather explicitly performs writes](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/vault_write_lookup.html#ansible-collections-community-hashi-vault-vault-write-lookup). That lookup was controversial, and I opted to include it because of certain operations in Vault that require a write in order to retrieve information (like generating a new secret ID for an approle).

But even if were to implement such a lookup, there is not a clean way I can think of to select a secret backend, so it would probably be dedicated to a single particular backend like kv2 or kv1 or cubbyhole, making it somewhat less flexible.

In addition, the secret "not existing" could be taken to mean that either the secret path itself doesn't exist, or that the secret exists but a particular key in the secret does not exist. These require different handling and operations, but I'll assume the former for now.

This type of lookup might be something I'd consider accepting a contribution for, but I'd have to give it more thought.

---

In the meantime, there re some alternatives.

You could create your own lookup independently of this collection. It's possible to use the module_utils of a collection from outside the collection, so you could take advantage of the shared code that exists here: https://github.com/ansible-collections/community.hashi_vault/tree/main/plugins/module_utils
But please understand that we explicitly mark these utils as being for internal use, and we do not guarantee API stability for them, nor announce those changes.

You can also create a lookup that internally calls other lookups; for example your lookup plugin could make calls using the existing `community.hashi_vault.vault_kv2_get` and `community.hashi_vault.vault_write` lookups. In the case where it needs to generate a password it can even call `ansible.builtin.password` with a file of `/dev/null` to do the generation.

In the case of using anything but `token` or `none` auth, you should also make a call to `community.hashi_vault.vault_login` so that the chosen method does cause two separate login events for retrieval and writes, which would generate extra tokens.

This option ends up being less code for you to write, and it would be using stable APIs, but it may not be as straightforward either.

It should also be possible to do this with existing lookups in Jinja2, although it may be a bit cumbersome. Here's an example that doesn't take into account single login, and is not tested at all.

It assumes you have a secret path `some_secret` with a sub-path that matches the short name of the current host (it could just as easily be shared among all hosts, or interpolated differently).

```yaml
- hosts: myhosts
  vars:
    ansible_hashi_vault_auth_method: token
    ansible_hashi_vault_token: "{{ my_token }}"
    ansible_hashi_vault_engine_mount_point: secret
    path: "some_secret/{{ inventory_hostname_short }}"
    write_path: "{{ ansible_hashi_vault_engine_mount_point }}/data/{{ path }}"
    secret_key: passwd
    secret: >-
      {{
        lookup('community.hashi_vault.vault_kv2_get', path, errors='ignore')
        | ternary(
          lookup('community.hashi_vault.vault_kv2_get', path).secret[secret_key],
          lookup('community.hashi_vault.vault_write', write_path, data=lookup(
            'ansible.builtin.password', '/dev/null', seed=inventory_hostname_short
          )) | default({}, True) | dict2items | reject('==', 0) | reject('!=', 0) | default(
          lookup('community.hashi_vault.vault_kv2_get', path).secret[secret_key],
          True
          )
        )
      }}
  tasks:
    - ansible.builtin.debug:
        var: secret
```

There are almost certainly mistakes here, and it makes lots of unnecessary calls; there might be ways to improve this in pure jinja as well. It's obviously really messy, but as you can see once the initial thing is defined, you need only reference it by var to execute it each time since templating is lazy.
