### DISCUSSION TITLE
Support for list=true parameter in the path

### DISCUSSION THREAD

**Discussion by faster-now** [ansible-collections/community.hashi_vault#339] [Q&A]
When using `vault_read` to try and perform a list operation it seems the only exposed attribute is path however adding `?list=true` to the end of the path results in an error stating the path doesnt seem to exist:

Example:
```yaml
    - name: Check if the role exists
      community.hashi_vault.vault_read:
        url: "https://127.0.0.1:8200"
        path: 'pki/roles?list=true'
        token: "{{ token }}"
        token_validate: false
      register: roles_list_result
```
Response:
```
["msg": "The path 'pki/roles?list=true' doesn't seem to exist."](fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "The path 'pki/roles\\?list=true' doesn't seem to exist."})
```

Despite experimenting and googling I cannot see how to use the `vault_read` to perform a list operation.
What am I missing?
