### DISCUSSION TITLE
ERROR! couldn't resolve module/action 'community.hashi_vault'.

### DISCUSSION THREAD

**Discussion by samderkaoui** [ansible-collections/community.hashi_vault#401] [Q&A] [answered]
Hello everyone. I was trying to use an ansible playbook with the community.hashi_vault 5.0.0 module, but i still have : ERROR! couldn't resolve module/action ...
I think i met all the requirements , if anyone has and idea ?

Thanks you very much for any help/ideas

edit : i also did it on another server, this time with almalinux 8.7 and it's the same error.

###############################
Here is all the information:

os : almalinux 9.2
###################################################
```
ansible --version
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/home/shed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/shed/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

###########################################

```
pip show hvac
Name: hvac
Version: 1.2.1
Summary: HashiCorp Vault API client
Home-page: https://github.com/hvac/hvac
Author: Ian Unruh
Author-email: ianunruh@gmail.com
License: Apache-2.0
Location: /home/shed/.local/lib/python3.9/site-packages
Requires: requests, pyhcl
Required-by:
```

###########################################

the begining of playbook ( it's just a test vault server dont worry :D )

```yaml
---
- name: Test
  hosts: localhost
  tasks:
    - name: test
      community.hashi_vault.hashi_vault:
        url: http://192.168.122.4:8200
        token: hvs.CAESIGALCSn9OLtiB-6BboaickZvQFIpAeNu2vpUDywbhsKmGh4KHGh2cy5NckhBYTZ4cjNrRXFZSUNFWkhHM0VwMHI
        secret: kv/foo
      register: vault_data
```

################################################# 
```
/home/shed/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
community.hashi_vault 5.0.0
```

####################################################

=> full error :   

```
ERROR! couldn't resolve module/action 'community.hashi_vault.hashi_vault'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/shed/play.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Read message from Vault
      ^ here
```

**Comment by briantist** [comment, marked as answer]
Hi @Kaiser016X , welcome!

The issue you have here is that [`community.hashi_vault.hashi_vault` is a lookup plugin](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup), and you are trying to use it as a module/action.

[Lookup plugins](https://docs.ansible.com/ansible/latest/plugins/lookup.html) are used inside Jinja2 templating, like `{{ lookup('community.hashi_vault.hashi_vault', ...) }}`.

This collection contains content other than the `hashi_vault` lookup, and many of those include both lookup and module forms.

First, I will recommend that you move away from `community.hashi_vault.hashi_vault` toward the other content in this collection. For details on how and why, see these guides:
- https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/docsite/migration_hashi_vault_lookup.html
- https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/docsite/about_hashi_vault_lookup.html

I also think it's a good idea to use modules instead of lookups in many cases, and there's information on that too:
- https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/docsite/lookup_guide.html

---

For your use case, I can't tell definitively from your example if you're using v1 or v2 of Vault's KV secrets engine. I will assume v2. For that, we have [the `vault_kv2_get` module](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/vault_kv2_get_module.html#ansible-collections-community-hashi-vault-vault-kv2-get-module).

So your example can be changed like so:

```yaml
---
- name: Test
  hosts: localhost
  tasks:
    - name: test
      community.hashi_vault.vault_kv2_get:
        url: http://192.168.122.4:8200
        token: hvs.CAESIGALCSn9OLtiB-6BboaickZvQFIpAeNu2vpUDywbhsKmGh4KHGh2cy5NckhBYTZ4cjNrRXFZSUNFWkhHM0VwMHI
        engine_mount_point: kv
        path: foo
      register: vault_data

- name: Display the secret
  ansible.builtin.debug:
    var: vault_data.secret
```

If you were using KVv1 instead, the example is exactly the same, except you would use [the `vault_kv1_get` module](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/vault_kv1_get_module.html#ansible-collections-community-hashi-vault-vault-kv1-get-module) instead.
