### DISCUSSION TITLE
write a policy

### DISCUSSION THREAD

**Discussion by p4r0d5** [ansible-collections/community.hashi_vault#439] [Q&A]
Dear all,
I dont find a way to use the community.hashi_vault.vault_write to write a policy. Could someone give me support on writing policies?
Thanks!

**Comment by MarcelKarras** [comment]
I'm also struggling on that... did you find a way? There's an old module named "hashivault_policy" but this seems outdated and is not part of this collection anymore. Can anyone help?

**Reply by p4r0d5** [reply]
I solved with a jinja template and curl post  with the shell module.

**Comment by MarcelKarras** [comment]
Found a way:

```yaml
---
- name: Write roles to vault
  community.hashi_vault.vault_write:
    url: "{{ vault_server }}"
    token: "{{ lookup('env', 'VAULT_TECH_ADMIN_TOKEN') }}"
    namespace: "my-namespace"
    path: "sys/policies/acl/{{ item.name }}"
    data:
      policy: "{{ item.rules }}"
  loop: "{{ vault_policies }}"

```
