### DISCUSSION TITLE
approle auth not working with vault_kv2_get lookup

### DISCUSSION THREAD

**Discussion by carlos-lehmann** [ansible-collections/community.hashi_vault#444] [Q&A] [answered]
Hey there,

Hope you're well! I'm seeking help with the lookup plugin `vault_kv2_get`

When I use the `vault` cli, with the approle to access a vault secret, everything works fine:

```bash
$ VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="408b1d9d-5b67-458a-8bc2-REDACTED" secret_id="4901a2fc-ced3-5cda-eb8d-REDACTED")
$ vault kv get -namespace=my_vault_namespace -field=my_field -mount=kv "my/kv-path/secret"
-----BEGIN RSA PRIVATE KEY-----
```

using `community.hashi_vault.vault_kv2_get` with ansible however fails:

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    ssh_dev: "{{ lookup('community.hashi_vault.vault_kv2_get', 'my/kv-path/secret', engine_mount_point='kv', url='https://REDACTED:443', namespace='my_vault_namespace', auth_method='approle', role_id='408b1d9d-5b67-458a-8bc2-REDACTED', secret_id='4901a2fc-ced3-5cda-eb8d-REDACTED')['secret']['my_field'] }}" 
    
  - name: Print ssh_dev
    ansible.builtin.debug:
      var: ssh_dev
```

output:
```yaml
TASK [Print ssh_dev] ****************************************************************************************************************************************************************************************************************************
task path: //path/to/mytask.yml:49
Loading collection community.hashi_vault from /Users/carlos/.ansible/collections/ansible_collections/community/hashi_vault
[WARNING]: Collection community.hashi_vault does not support Ansible version 2.11.4
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{{ lookup('community.hashi_vault.vault_kv2_get', 'my/kv-path/secret', engine_mount_point='kv', url='https://REDACTED:443', namespace='my_vault_namespace', auth_method='approle', role_id='408b1d9d-5b67-458a-8bc2-REDACTED', secret_id='4901a2fc-ced3-5cda-eb8d-REDACTED' )['secret']['my-field'] }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.vault_kv2_get'. Error was a <class 'hvac.exceptions.Forbidden'>, original message: permission denied, on post https://REDACTED:443/v1/auth/approle/login"
}
```

using the generated vault token `$VAULT_TOKEN` from `vault` cli (see above) instead of the approle works:

```bash
- hosts: localhost
  gather_facts: no
  vars:
    ssh_dev: "{{ lookup('community.hashi_vault.vault_kv2_get', 'my/kv-path/secret', engine_mount_point='kv', url='https://REDACTED:443', namespace='my_vault_namespace', token='hvs.CAESIIlgbqZ_eHD1SV5kE6EhutQ_TSBqpkwDtssxlz0EeuYmGiUKHGh2cyREDACTED' )['secret']['my_field'] }}" 
```

output:
```yaml
TASK [Print ssh_dev] ****************************************************************************************************************************************************************************************************************************
task path: /path/to/mytask.yml:49
Loading collection community.hashi_vault from /Users/REDACTED/.ansible/collections/ansible_collections/community/hashi_vault
[WARNING]: Collection community.hashi_vault does not support Ansible version 2.11.4
ok: [localhost] => {
    "ssh_dev": "-----BEGIN RSA PRIVATE KEY-----
```

gpt is telling me that the plugin does authentication for me, I couldn't find the code snippet so any help appreciated if I have missed something obvious.

Cheers,
Carlos

**Comment by ji-podhead** [comment]
i dont get this to work either. i really tried to get this to work for almost 2 days now.
i tried the lookup version but it tell me that theres no url specified, so i tried the other method like this:
```yaml
- hosts: host1
  gather_facts: no
  tasks:
    - name: damn
      vars:
        ansible_hashi_vault_auth_method: token
        ansible_hashi_vault_token: <my token>
        ansible_hashi_vault_engine_mount_point: "data/ansible/proxmox/dc-workshop1"
        ansible_hashi_vault_url: http://127.0.0.1:8200
      ansible.builtin.debug:
        msg: '{{ item.values() | list }}'
      with_community.hashi_vault.vault_kv2_get:
        - user
```
this is the error this method is producing:
`{"msg": "Invalid or missing path ['user'] with secret version 'latest'. Check the path or secret version."}`

---

so i just use the curl version now:
```
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get all secrets under a specific path
      uri:
        url: http://127.0.0.1:8200/v1/keyvalue/data/ansible/proxmox/dc-workshop1
        method: GET
        return_content: yes
        headers:
          X-Vault-Token: <my token>
      register: result

    - name: Print all secrets
      debug:
        var: result.json.data
   ```

**Reply by ji-podhead** [reply]
would be awesome if there was a proper video or example  for this thing

**Reply by carlos-lehmann** [reply]
It might be that your `engine_mount_point` is wrong. Check issue: https://github.com/ansible-collections/community.hashi_vault/issues/279 the default is `secret`. In my case it's `kv` and yours is `data/ansible/proxmox/dc-workshop1` but that seems to me like the path to your secret [and not the mount point](https://www.reddit.com/r/hashicorp/comments/yv99v8/comment/iwd3n6w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

**Reply by briantist** [reply]
yes @carlos-lehmann is correct, you should not be including KV2's `data` in the mount point (nor in the path).

**Comment by carlos-lehmann** [comment]
I've tried with env variables instead: 
`ANSIBLE_HASHI_VAULT_AUTH_METHOD`
`ANSIBLE_HASHI_VAULT_ROLE_ID`
`ANSIBLE_HASHI_VAULT_SECRET_ID` 
with no luck, same error.

further proof when I do a curl to vault with approle `role_id` and `secret_id`:

```bash
curl --request POST --data '{"role_id": "408b1d9d-5b67-458a-8bc2-REDACTED", "secret_id": "4901a2fc-ced3-5cda-eb8d-REDACTED"}' https://REDACTED:443/v1/auth/approle/login
```

I get: 

<code>{"request_id":"b7ccebf0-82a0-4820-3f7e-083f40c5150e","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":null,"auth":{"client_token":"hvs.REDACTED","accessor":"REDACTED","policies":["approle (auth_approle_REDACTED) 408b1d9d-5b67-458a-8bc2-REDACTED manager","default"],"identity_policies":["approle (auth_approle_REDACTED) 408b1d9d-5b67-458a-8bc2-REDACTED manager","default"],"metadata":{"role_name":"408b1d9d-5b67-458a-8bc2-REDACTED"},"lease_duration":3600,"renewable":true,"entity_id":"REDACTED","token_type":"service","orphan":true,"mfa_requirement":null,"num_uses":0}}</code>

So generally speaking I can use the approle `role_id` and `secret_id` to authenticate to Vault and get a token back. Authentication just doesn't work with the Plugin :-(

Any further help to find the issue would be much appreciated!

**Comment by carlos-lehmann** [comment]
Some progress on my side... the problem is that authentication happens on the root namespace not on the one I give for the kv secret. Because of that either the login works with `vault_kv2_get` and then fetching the secret doesn't. Instead I'm now doing a login with `vault_login` plugin to get the token and then use that token to fetch the secret.

```
  tasks:
  - name: "login to vault"
    community.hashi_vault.vault_login:
      url: https://REDACTED:443
      auth_method: approle
      role_id: '408b1d9d-5b67-458a-8bc2-REDACTED'
      secret_id: '4901a2fc-ced3-5cda-eb8d-REDACTED'
    register: login_result

  - name: "Set vault_token as a fact"
    set_fact:
      vault_token: "{{ login_result['login']['auth']['client_token'] }}"

  - name: "Set secret data as a fact"
    set_fact:
      ssh_dev: "{{ lookup('community.hashi_vault.vault_kv2_get', 'my/kv/path', engine_mount_point='kv', namespace='my_namespace', token=vault_token, url='https://REDACTED:443')['secret']['my_field'] }}"
```
