### DISCUSSION TITLE
vault auth enable?

### DISCUSSION THREAD

**Discussion by MuhKuh7** [ansible-collections/community.hashi_vault#457] [Q&A]
Is there any way to do a "vault auth enable kubernetes"?

**Comment by briantist** [comment]
https://developer.hashicorp.com/vault/api-docs/system/auth#enable-auth-method

We don't have a dedicated plugin or module for this but you should be able to achieve it using `vault_write` and providing the correct path and data.

**Comment by mmdfaisal1** [comment]
Hi @briantist I am looking for something similar and found my way here. I want to do `vault auth enable ldap`

I am trying to figure out how to do this through `vault_write` as you suggested above. Could you provide some help?

I am currenly using `ansible.builtin.command` tasks to achieve the above and have idempotency, as below

```yaml
    - name: Check if LDAP auth is already enabled
      ansible.builtin.command: "{{ vault_base_dir }}/bin/vault auth list -format=json"
      environment:
        VAULT_ADDR: "https://{{ vault_server_name }}"
        VAULT_TOKEN: "{{ vault_root_token }}"
      become_user: "{{ vault_user }}"
      register: auth_list
      changed_when: false

    - name: Parse auth methods
      ansible.builtin.set_fact:
        ldap_enabled: "{{ 'ldap/' in (auth_list.stdout | from_json) }}"

#    - name: Debug ldap_enabled state
#      ansible.builtin.debug:
#        msg: "ldap_enabled value is {{ ldap_enabled }}"

    - name: Enable LDAP authentication
      ansible.builtin.command: "{{ vault_base_dir }}/bin/vault auth enable ldap"
      environment:
        VAULT_ADDR: "https://{{ vault_server_name }}"
        VAULT_TOKEN: "{{ vault_root_token }}"
      become_user: "{{ vault_user }}"
      when: not ldap_enabled
      changed_when: true
      
 ```

**Reply by briantist** [reply]
Hi @mmdfaisal1 I don't have ready made examples, here's an idea how it could be done but these are not tested and may need tweaks:

```yaml
- name: LDAP Auth
  vars:
    ldap_enabled: "{{ 'ldap/' in auth_list.data }}"
  module_defaults:
    group/community.hashi_vault.vault:
      auth_method: token
      token: "{{ vault_root_token }}"
      url: "https://{{ vault_server_name }}"
  block:
    # https://developer.hashicorp.com/vault/api-docs/system/auth#list-auth-methods
    - name: Check if LDAP auth is already enabled
      register: auth_list
      community.hashi_vault.vault_list:
        path: sys/auth

    # https://developer.hashicorp.com/vault/api-docs/system/auth#enable-auth-method
    - name: Enable LDAP auth
      when: not ldap_enabled
      community.hashi_vault.vault_write:
        path: sys/auth/ldap
        data:
          type: ldap
          description: <optional>
          config:  #optional
            default_lease_ttl: <some value>
            # <more config options>
```

See the linked docs for the API on what additional config options and other data you can pass in.

Also both the above example and yours assume mounting the LDAP auth method at the default path of `ldap/` (they also assume that the auth method mounted at the `ldap/` path is actually of type `ldap` which does not have to be the case). 

If you wanted to mount it on a different path and/or check the type, you need to change both tasks. In this modified example, the mount point is a variable `ldap_mount_point`:

```yaml
- name: LDAP Auth
  vars:
    ldap_mount_point: corp-directory
    ldap_enabled: "{{ auth_list.data[ldap_mount_point~ '/'].type | default(None) == 'ldap' }}"
  module_defaults:
    group/community.hashi_vault.vault:
      auth_method: token
      token: "{{ vault_root_token }}"
      url: "https://{{ vault_server_name }}"
  block:
    # https://developer.hashicorp.com/vault/api-docs/system/auth#list-auth-methods
    - name: Check if LDAP auth is already enabled
      register: auth_list
      community.hashi_vault.vault_list:
        path: sys/auth

    # https://developer.hashicorp.com/vault/api-docs/system/auth#enable-auth-method
    - name: Enable LDAP auth
      when: not ldap_enabled
      community.hashi_vault.vault_write:
        path: sys/auth/{{ ldap_mount_point }}
        data:
          type: ldap
          description: <optional>
          config:  #optional
            default_lease_ttl: <some value>
            # <more config options>
```
