### ISSUE TITLE
Support writing to Vault

### ISSUE THREAD

**Issue by horazont** [ansible-collections/community.hashi_vault#174]
##### SUMMARY
Support writing to Vault. Like `vault_read`, there should be a `vault_write` action. This is useful with secrets engines which use writes to generate data, such as PKI (generating a certificate), SSH (signing a key) etc.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
New, I guess? (Sorry, I don't really have a clue what is meant by "component" here)

##### ADDITIONAL INFORMATION
This is how I imagine it could look, using the [SSH engine](https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates#host-key-signing) as an example:

```yaml
- name: sign SSH host key
  community.hashi_vault.write:
    path: ssh/sign/rolename
    data:
      public_key: "{{ the_nodes_public_key }}"
      cert_type: host
    register: signed_key

- name: display signed key
  debug:
    msg: "my signed key is: {{ signed_key.data.signed_key }}"
```
