### ISSUE TITLE
hashi_vault_write bug or feature ?

### ISSUE THREAD

**Issue by rouja** [ansible-collections/community.hashi_vault#254]
Hi everyone !

##### SUMMARY
The documentation shows us this example :

```
- name: Write a value to the cubbyhole via the remote host with userpass auth
  community.hashi_vault.vault_write:
    url: https://vault:8201
    path: cubbyhole/mysecret
    data:
      key1: val1
      key2: val2
    auth_method: userpass
    username: user
    password: '{{ passwd }}'
  register: result
```

In my case I use environment variable to connect to vault so I simplified the example like that : 

```
- name: Write a value to the cubbyhole via the remote host with userpass auth
  community.hashi_vault.vault_write:
    path: cubbyhole/mysecret
    data:
      key1: val1
      key2: val2
```

Which work perfectly with the cubbyhole but not with kv engine (v2 in my case):

```
- name: Write a value to the cubbyhole via the remote host with userpass auth
  community.hashi_vault.vault_write:
    path: secret/data/mysecret
    data:
      key1: val1
      key2: val2
```

We got this error : 

```
File \"/home/jroussel/Git/qwant/venv/lib/python3.10/site-packages/hvac/utils.py\", line 32, in raise_for_error\n    raise exceptions.InvalidRequest(message, errors=errors)\nhvac.exceptions.InvalidRequest: no data provided\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1
```

At the beginning I thought it's was python bug. But then I remembered that with curl we do something like :

```
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"data":{"test":"tutu"},"options":{}}' http://localhost:8200/v1/secret/data/mysecret
```

So I changed ansible task by :

```
- name: Write a value to the cubbyhole via the remote host with userpass auth
  community.hashi_vault.vault_write:
    path: secret/data/mysecret
    data:
      data:
        key1: val1
        key2: val2
  ```

And It works.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.hashi_vault.vault_write

##### ANSIBLE VERSION
I tested with multiple ansible version from 2.9.20 to the last version.

##### COLLECTION VERSION
```
2.4.0
```

So, is it a bug or is it normal ? If it's normal, maybe the documentation should be update ?

Have a nice day
