### ISSUE TITLE
Support GitHub (Or Generic) Authentication

### ISSUE THREAD

**Issue by rfpludwick** [ansible-collections/community.hashi_vault#346]
##### SUMMARY

Vault supports [GitHub authentication](https://developer.hashicorp.com/vault/docs/auth/github). Please either directly support it in this collection, or allow for a generic authentication method like what HashiCorp have done with [Terraform's Vault provider](https://registry.terraform.io/providers/hashicorp/vault/latest/docs#generic).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Unsure...

##### ADDITIONAL INFORMATION

Some folks have home labs, like me, and are using Vault with GH auth for simplicity's sake.

This could be an approach in allowing generic auth, rather than specifically GitHub. This mimics HashiCorp's approach.

```yaml
auth_method: generic
auth_path: auth/github/login
auth_params:
  token: abcxyz
```
