### ISSUE TITLE
Required Index Not Present

### ISSUE THREAD

**Issue by mjnorman** [ansible-collections/community.hashi_vault#393]
##### SUMMARY
Utilizing Approle auth with `community.hashi_vault.vault_kv1_get` produces error of `"msg": "An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.vault_kv1_get'. Error was a <class 'hvac.exceptions.UnexpectedError'>, original message: ['required index state not present']`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vault_kv1_get

##### ANSIBLE VERSION

2.11

```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
4.1.0

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
  tasks:

    - name: Provide Appdynamics
      vars:
        ansible_hashi_vault_auth_method: approle
        ansible_hashi_vault_role_id: some_role
        ansible_hashi_vault_secret_id: some_secret
        ansible_hashi_vault_engine_mount_point: mount_point
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.vault_kv1_get', 'path/to/secret').secret.somesecret}}"

```

##### EXPECTED RESULTS

secret should be returned

##### ACTUAL RESULTS

```yaml
{
  "msg": "An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.vault_kv1_get'. Error was a <class 'hvac.exceptions.UnexpectedError'>, original message: ['required index state not present'], on get https://vault:secret",
  "_ansible_no_log": false
}
```

```paste below
{
  "msg": "An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.vault_kv1_get'. Error was a <class 'hvac.exceptions.UnexpectedError'>, original message: ['required index state not present'], on get https://vault:secret",
  "_ansible_no_log": false
}
```
