### ISSUE TITLE
Documentation about `auth_method` 'none' hashi_vault 

### ISSUE THREAD

**Issue by Fabiokleis** [ansible-collections/community.hashi_vault#395]
##### SUMMARY

```yml
- name: authenticate with vault agent
  ansible.builtin.debug:
    msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/hello:value', auth_method='none', url='http://127.0.0.1:8100') }}"

```

I'm trying to understand how this works, I'm using vault agent to authenticate but I didn't understand how the `hashi_vault` retrives the token. In my agent configuration I save the token in a file in `/tmp` and after reading roleid and consuming secretid the ansible playbook works as espected.

I'm studying about the authentication methods, and I think would be nice if exist a way to pass the path of the token file generated by vault agent.

##### ISSUE TYPE
- Documentation Report
