### ISSUE TITLE
Where is url in with_community.hashi_vault.vault_read?

### ISSUE THREAD

**Issue by mihalt** [ansible-collections/community.hashi_vault#436]
hi! Very looks like that there is error in docs https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/vault_read_lookup.html#examples

In this place
```
- name: Perform multiple reads with a single Vault login in a loop (via with_)
  vars:
    ansible_hashi_vault_auth_method: userpass
    ansible_hashi_vault_username: '{{ user }}'
    ansible_hashi_vault_password: '{{ pwd }}'
  ansible.builtin.debug:
    msg: '{{ item }}'
  with_community.hashi_vault.vault_read:
    - secret/data/hello
    - auth/approle/role/role-one/role-id
    - auth/approle/role/role-two/role-id
 ```

So, I have error like this when I try to execute this command `{"msg": "Unexpected failure during module execution: Required option url was not set."}`
