### ISSUE TITLE
vault_kv2_delete: Add posibility to destroy

### ISSUE THREAD

**Issue by Kloppi313** [ansible-collections/community.hashi_vault#446]
##### SUMMARY
It is not possible to destroy something in vault.
I think a boolean switch would be great:

Adding something like the parameter `destroy: True/False` with standard false would do the trick.

The context is the wish to [destroy an entire secret with all versions](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#delete-metadata-and-all-versions) while decomissining a host with its saved secrets.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vault_kv2_delete

##### ADDITIONAL INFORMATION

```yaml
- name: Delete all of the secret/mysecret secret.
  community.hashi_vault.vault_kv2_delete:
    url: https://vault:8201
    path: secret/metadata/mysecret
    auth_method: userpass
    username: user
    password: '{{ passwd }}'
    destroy: True
  register: result
```
