### ISSUE TITLE
hashi_vault - lookup failed with connection error

### ISSUE THREAD

**Issue by SJay3** [ansible-collections/community.hashi_vault#62]
##### SUMMARY
Hi! we got a randomly error with hashi_vault lookup plugin
```
Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'community.general.hashi_vault'. Error was a <class 'requests.exceptions.ConnectionError'>, original message: HTTPSConnectionPool(host='vault.example.com', port=80): Max retries exceeded with url: /v1/auth/token/lookup-self (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fa81917b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))"
```
It doesn't seems that it hc vault server error. we couldn't find anything unusual on server side.
We need to know why this error is happened. Sometimes everything fine, sometimes not.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.general.hashi_vault

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /mnt/d/git/myoffice/ansible_playbooks/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dusachev/.local/lib/python3.6/site-packages/ansible
  executable location = /home/dusachev/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

here is example playbook that we use

```yaml
---

- name: "Vault test playbook"
  hosts: testhost
  tasks:
    - name: "facts"
      set_fact:
        vault_secrets:
          secret1: "{{ lookup('community.general.hashi_vault', 'kv/data/stands/teststand/secret1') }}"
          secret2: "{{ lookup('community.general.hashi_vault', 'kv/data/stands/teststand/secret2') }}"
          secret3: "{{ lookup('community.general.hashi_vault', 'kv/data/stands/teststand/secret3') }}"
          secret4: "{{ lookup('community.general.hashi_vault', 'kv/data/stands/teststand/secret4') }}"
          secret5: "{{ lookup('community.general.hashi_vault', 'kv/data/stands/teststand/secret5') }}"
          secret6: "{{ lookup('community.general.hashi_vault', 'kv/data/stands/teststand/secret6') }}"
```

##### ACTUAL RESULTS

```paste below

```
