### ISSUE TITLE
hashi_vault - Can't login using username/password (userpass auth method)

### ISSUE THREAD

**Issue by joao-p-marques** [ansible-collections/community.hashi_vault#66]
##### SUMMARY
I can use the lookup plugin to login with a user token, but I can't login using a **username and password**.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`hashi_vault` lookup plugin, possibly with the integration with the `hvac` library.

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = None
  configured module search path = ['/home/jota/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jota/Documents/Tecnativa/infra/ci-templates/.venv/lib/python3.9/site-packages/ansible
  executable location = /home/jota/Documents/Tecnativa/infra/ci-templates/.venv/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

##### CONFIGURATION

```paste below
```
(empty)

##### OS / ENVIRONMENT

Fedora 33, running a playbook against localhost (local connection)

##### STEPS TO REPRODUCE

I created a simple playbook just to test this case:

```yaml
- name: Test
  hosts: localhost
  connection: local
  vars:
    vault_username: MY_USER_NAME
    vault_password: MY_USER_PASSWORD
    vault_api: URL_TO_MY_SERVER
    vault_token: MY_USER_TOKEN
  tasks:
    - ansible.builtin.debug:
        msg:
          "{{ lookup('community.hashi_vault.hashi_vault',
          'secret=secret/data/SOME-SECRET/SUB-SECRET', token=vault_token, url=vault_api)
          }}"
    - ansible.builtin.debug:
        msg:
          "{{ lookup('community.hashi_vault.hashi_vault',
          'secret=secret/data/SOME-SECRET/SUB-SECRET', auth_method='userpass',
          username=vault_username, password=vault_password, url=vault_api) }}"

```

##### EXPECTED RESULTS

Both cases should work (retrieve secrets with a token and with a username/password pair)

##### ACTUAL RESULTS

The first command (with a token) works (proving my user has access to said secret and that its token is valid)
The second command does not work, giving the following error:

```paste below
TASK [ansible.builtin.debug] *********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.hashi_vault'. Error was a <class 'hvac.exceptions.InvalidRequest'>, original message: missing client token, on get URL_TO_MY_SERVER/v1/secret/data/SOME-SECRET/SUB-SECRET"}
```

cc @Yajo
