### ISSUE TITLE
Allow to continue execution of plugin when secret not found or permission denied

### ISSUE THREAD

**Issue by joao-p-marques** [ansible-collections/community.hashi_vault#69]
##### SUMMARY

Allow the plugin to continue without failure when Vault returns a permission denied error or a value of `None` (secret does not exist)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`hashi_vault` lookup plugin

##### ADDITIONAL INFORMATION

Vault can return a permission denied error, or `None` data when the secret does not exist or the user does not have permission to access it. 
However, there might be situations where you need to follow the execution of the plugin and playbook, and it would be nice to get an empty answer instead of an exception thrown in those situations.

```yaml
- name: obtain secrets
      loop:
        - secret1
        - secret2
        - secret3
      set_fact:
        secrets_dict:
          "{{ secrets_dict | d({}) | combine( { item : lookup('community.hashi_vault.hashi_vault', 'secret/data/secrets/' + item, auth_method='userpass', password=vault_password, username=vault_username, url=vault_api, allow_failure=True) } )}}"
```

The `allow_failure` option would prevent those 2 exceptions from being thrown, but instead make the plugin return an empty value, which could be treated easily in Ansible.

cc @Yajo
